name: CI
env:
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
on:
  pull_request:
    types: [labeled, synchronize, edited]
    branches:
      - main
    paths-ignore:
      - ".nxignore"

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.pull_request.labels.*.name, 'PR status: review ready') }}"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.19.1"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        shell: bash
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        shell: bash
      - name: Setup Canvas
        run: npm rebuild canvas
      - name: Run test
        run: yarn test

  preview:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.pull_request.labels.*.name, 'PR status: review ready') }}"
    timeout-minutes: 10
    environment: testing
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.19.1"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        shell: bash
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        shell: bash
      - name: Pull Vercel Environment Information
        run: npx dotenv -v VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} -v VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} -- vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        shell: bash
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        shell: bash
      - name: Deploy Project Artifacts to Vercel
        id: preview-deployment
        run: echo "GITHUB_PREVIEW_URL=$(npx dotenv -v VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} -v VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} -- vercel --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_ENV
        shell: bash
      - name: Generate Preview Link
        id: preview-link
        run: echo "::set-output name=url::$GITHUB_PREVIEW_URL"
        shell: bash
      - name: Add the preview report to pull request
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{ env.GITHUB_PREVIEW_URL }}
          proxy-url: ${{ steps.preview-deployment.outputs.result }}
